language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
before_deploy:
  - echo 'ready to deploy?'
deploy:
  - provider: npm
    email: "ameya.n2007@gmail.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build
    on:
      branch: master